name: 3D Contribution Grid

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          USERNAME: TheClazer
      - name: commit & push
        run: |
          git config user.name "TheClazer"
          git config user.email "therayyn16@gmail.com"
          git add profile-3d-contrib
          git diff --staged --quiet || git commit -m "chore: refresh 3d contribution grid"
          git push
